[pytest]
testpaths = tests
addopts = -v --strict-markers --alluredir=allure-results --clean-alluredir --video=retain-on-failure --tracing=retain-on-failure --output=test-results
markers =
    api: API-тесты
    ui: UI-тесты (Playwright)
